### ISSUE TITLE
Train model with OxIOD data

### ISSUE THREAD

**Issue by smorantg2** [Sachini/ronin#10]
Hi,

I have been using the pretrained models with data collected from my smartphone through the Android App (w/o tango) with really impressive results while walking or wandering around. 
However, the models fail to predict the trajectory whenever I start running. I would like to train the model with running data from the OxIOD dataset, but I don't fully understand the transformations needed to do so. 

I am able to convert the data to the RIDI format (gyro, acce, rv, pos, ori), but it seems converting the acceleration units and attitude_(x,y,z) from OxIOD to quaternions for rv_(w,x,y,z) is not enough or correct. 

Could you please give me some insight about how to do it? Am I missing something?

Your help is very much appreciated!

**Comment by Sachini** [comment]
Acceleration and attitude to quaternion are the conversions we used too. (But we found that Android device reference frame and Vicon device reference frame is not consistently calibrated). It would be best to contact authors of the dataset.

If you are planning to use multiple datasets, you'd need to adjust the reference frame difference in accelerometer between Android and iOS APIs.
