### ISSUE TITLE
train with gpu but the computer always restarts

### ISSUE THREAD

**Issue by liubamboo** [Sachini/ronin#11]
When I train the ronin_resnet with gpu, the computer always restart
Compilation is falling back to object mode WITH looplifting enabled because Function "change_cf" failed type inference due to: No implementation of function Function(<function repeat at 0x7f8817b93378>) found for signature:
 
 >>> repeat(list(array(float32, 1d, A))<iv=None>, int64, axis=Literal[int](0))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'np_repeat': File: numba/np/arrayobj.py: Line 1925.
    With argument(s): '(list(array(float32, 1d, A))<iv=None>, int64, axis=int64)':
   Rejected as the implementation raised a specific error:
     TypeError: np_repeat() got an unexpected keyword argument 'axis'
  raised from /home/lwt/anaconda3/envs/py36-for-ronin/lib/python3.6/site-packages/numba/core/typing/templates.py:710

During: resolving callee type: Function(<function repeat at 0x7f8817b93378>)
During: typing of call at /mnt/mdisk/lwt/project/ronin/source/transformations.py (21)

File "transformations.py", line 21:
def change_cf(ori, vectors):
    <source elided>
    if len(ori.shape) == 1:
        ori = np.repeat([ori], vectors.shape[0], axis=0)
        ^

  @jit('f8[:,:](f4[:],f4[:, :])')
/home/lwt/anaconda3/envs/py36-for-ronin/lib/python3.6/site-packages/numba/core/object_mode_passes.py:178: NumbaWarning: Function "change_cf" was compiled in object mode without forceobj=True.

File "transformations.py", line 10:
@jit('f8[:,:](f4[:],f4[:, :])')
def change_cf(ori, vectors):
^

  state.func_ir.loc))
/home/lwt/anaconda3/envs/py36-for-ronin/lib/python3.6/site-packages/numba/core/object_mode_passes.py:188: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

**Comment by Sachini** [comment]
Thank you. I have removed the numba signature to be compatiable with latest versions
