### ISSUE TITLE
Are ground truth position (pose/tango_pos) and IMU data (synced/gyro_uncalib) from different device?

### ISSUE THREAD

**Issue by tonyke1993** [Sachini/ronin#16]
Thanks for sharing the datasets.
From your paper, it seems that the ground truth is from the phone attached to the body while the IMU data are from the phone holding on the hand.
Is this the case? So the ground truth position at least has errors on the level of several decimetres?

How about the ground truth orientation? Is it from the device of IMU data?

**Comment by anisghaoui** [comment]
From what I understood, they use the Google Tango phone as ground truth. that phone performs a visual inertial SLAM which is accurate enough to be considered a ground truth.

The IMU phones are used to extract IMU data, train and test the models.

**Comment by Sachini** [comment]
Yes, the data is collected from two devices as described above. 

Can you clarify what you meant by error in ground-truth? Our ground-truth defines the 3 DoF pose of the subject and not the IMU device. Please refer to section 3 of the paper for the task definition. 

Filtered orientations (see section 3.1 of supplementary material) in "synced/ekf_ori" provides an approximation for the orientation of IMU device however we do not have an accuracy guarantee for this.

**Comment by tonyke1993** [comment]
By error in ground-truth, I mean the provided ground-truth is not the true trajectory of the IMU phone, but an approximated one using the trajectory of the 3D tracking phone.

Is "synced/ekf_ori" from the IMU phone? It is from IMU only or from tango's visual inertial slam? I understand the latter is not reliable when camera is covered, e.g., the phone is in the pocket.

**Comment by Sachini** [comment]
Our task is to track the trajectory of **person** not the  **IMU phone**, so the ground-truth is the pose of the person and not the device. GT for person is obtained by the Tango phone which is fixed wrt to body. We don't have ground-truth pose for the IMU device.

The Tango phone was never covered during data collection. You can find the details of data collection and filtered orientation in supplementary material [here](https://arxiv.org/pdf/1905.12853.pdf)

**Comment by tonyke1993** [comment]
I see. Thanks!
