### ISSUE TITLE
Device position metadata (in handbag, pocket, hand, etc)

### ISSUE THREAD

**Issue by jhultman** [Sachini/ronin#18]
Hi, thanks for sharing your code and data. I was wondering if you have a table indicating which sequences correspond to which device placements? See example below.

Sequence | Device placement
------------- | ------------------------
a000_1     | Pocket
a000_2     | Hand
a001_1     | Handbag
a003_1     | Pocket

Or did the subjects not carry the device in the same manner throughout each sequence? Maybe this is what you meant by "natural motion." I couldn't tell from the paper. Thanks!

**Comment by Sachini** [comment]
It's the latter. The subjects changed the device placement multiple types during a trajectory. The placements include hand, pocket, 
 and bag, but not restricted to those as we allowed any natural placement. We don't have placement annotation for the data
