### ISSUE TITLE
is Tango Data Required For Test Sequence?

### ISSUE THREAD

**Issue by smoothumut** [Sachini/ronin#25]
Hi thanks for the great work, 
I created data using imu recorder and convert it into hdf5 file using "compile_unannotated_sequence" function in compile_dataset_h5.py file. I have used 'gyro', 'gyro_uncalib', 'acce', 'linacce', 'gravity', 'magnet','game_rv', 'rv' 'pressure' datas.

Naturally it doesnt have pose data which contains tango_pose and tango_ori BUT get_dataset function for RONIN in "test sequence" function requires that tango data ! What am I missing??
Regards

**Comment by smoothumut** [comment]
Hi again, I want to refresh my question;

I have found the way of creating gyro_bias.txt but not "acce_calib.txt" file yet. 

In order to create hdf5 file and test with your pretrained model with that hdf5 file, I want to use "compile_unannotated_sequence" function in compile_dataset_h5.py file 
1 - am I on the right track? yes or no
2 - is "acce" in that function is Android Sensor.TYPE_ACCELEROMETER  or TYPE_ACCELEROMETER_UNCALIBRATED in android?
3 - how can I get/create "acce_scale" in android?

thanks thanks thanks in advance

**Comment by smoothumut** [comment]
Hi, I am moving forward but I come across new problems to understand. 
So I want to refresh my question once again

my new questions are:

1- according to your answers I see in other issues, I understand that info.json is for training purposes, so I wont need ekf_ori_error,gyro_integration_error and grv_ori_error .    Am I right?

2- I created data using imu recorder and convert it into hdf5 file using "compile_unannotated_sequence" function in compile_dataset_h5.py file, and it doesnt have pose that contains tango_pose and tango_ori BUT get_dataset function for ronin in test sequence requires that tango data !    What am I missing??

thanks thanks in advance

**Comment by Sachini** [comment]
You can run the models without Tango data but this would need some modifications to the preprocessing scripts OR dataloader. 

 - run `compile_dataset_h5.py` with `--type unannotated` and assign identity values for any missing fields in calibration (if not done) and/or tango datastreams. 
(e.g : imu_acce_bias = [0,0,0], imu_acce_bias = [1, 1, 1] ,  start_calibration=[1, 0, 0, 0] etc..). You can assign tango_pos = np.zeros(length, 3),
 
- tango_ori needs to be a gravity aligned orientation. So you can one of the following
    1.  copy values of game_rv to tango_ori , or
    2. remove lines 56-58 in data_glob_speed.py
 
- run models using the given command

**Comment by smoothumut** [comment]
Thanks for your detailed answer, I was about to lose hope : ) 
It really helped Regards

**Comment by OmerTariq-KAIST** [comment]
> You can run the models without Tango data but this would need some modifications to the preprocessing scripts OR dataloader.
> 
> * run `compile_dataset_h5.py` with `--type unannotated` and assign identity values for any missing fields in calibration (if not done) and/or tango datastreams.
>   (e.g : imu_acce_bias = [0,0,0], imu_acce_bias = [1, 1, 1] ,  start_calibration=[1, 0, 0, 0] etc..). You can assign tango_pos = np.zeros(length, 3),
> * tango_ori needs to be a gravity aligned orientation. So you can one of the following
>   
>   1. copy values of game_rv to tango_ori , or
>   2. remove lines 56-58 in data_glob_speed.py
> * run models using the given command

Hi. Can you explain this : " You can assign tango_pos = np.zeros(length, 3)"?
where do I assign this?
