### ISSUE TITLE
IMURecorder accurate timestamps

### ISSUE THREAD

**Issue by jhultman** [Sachini/ronin#27]
Hi, I was wondering if it is possible to obtain milli/micro-second precision timestamps from the IMURecorder app? It seems the app produces a header for each CSV file with the phone boot time, and the per-packet timestamps are then measured in nanoseconds elapsed since the boot time. However, the header time is in `hh:mm:ss` format and so cannot be used to obtain the accurate timestamp.

I want to synchronize Android clock with NIST atomic clock and then obtain accurate UTC timestamps for the sensor data, to make it easy to align with ground truth obtained on another system. Is this possible? Can you release the java source code for IMURecorder? What is the purpose of `reference_time.txt` which seems to always have value `0`? Can I change the reference time somehow? Thank you!

Example abbreviated `gyro.txt` for your reference:

```
# Created at Fri Apr 23 03:53:31 GMT+07:00 2021
14378659749280 0.013057 0.190590 0.018097
...
```

**Comment by Sachini** [comment]
We found that the wall clock timestamps are not always linearly increasing in Android, so we chose to syncronize the nanosecond time between devices. 

The reference_time.txt is the coarse synchronization when connected via Bluetooth, and is only valid when two devices are used in master-slave mode. We manually selected the data gyro data for fine-tuning the coarse syncronization, as described in `Time synchronization` in the supplementary paper.

We cannot release the code for app or the preprocessing in two device setting unfortunately. If you need to modify, our app is an improved version of https://github.com/higerra/AndroidIMURecorder from RIDI

**Comment by jhultman** [comment]
Thank you for your response. I will reach out if I have further questions.

**Comment by uta-codyl** [comment]
Hi @Sachini 
Looking at the repo from higerra we cannot build and run the app. 
Do you know what IDE and build method was used for that app?

**Comment by Sachini** [comment]
Sorry, I'm not the maintainer of the repo, so not sure if its up-to-date.
We use Android Studio for development
