### ISSUE TITLE
Tango Device, Unfortunately, SLAMRecorder has stopped

### ISSUE THREAD

**Issue by logindiamant** [Sachini/ronin#28]
Dear colleagues, I install App for Google Tango Device on Lenovo Phab 2 Pro
But, app not run with error "Unfortunately, SLAMRecorder has stopped"
What settings need to run app?

With regards

**Comment by Sachini** [comment]
Hi, 
The APK released is build on Android SDK 26 (min SDK 23) and tango:sdk-base:1.55. The required permissions will be displayed upon installation. You'd need WiFi, location and Bluetooth to be turned on when running the app.

If you still run in to issues, try debugging using this source code, https://github.com/higerra/AndroidIMURecorder. (There are some minor differences from our app, but the basic functionality is the same)

**Comment by logindiamant** [comment]
@lonlonago now 2 apps work perfect on my two Lenovo Phab 2 Pro
https://drive.google.com/file/d/1xJHZ_O-uDSJdESJhZ3Kpy86kWaGX9K2g
https://drive.google.com/file/d/1BVhfKE6FEL9YRO1WQCoRPgLtVixDbHMt
Thanks, @Sachini @higerra
