### ISSUE TITLE
How can I generate the preprocess data like ori_error.json

### ISSUE THREAD

**Issue by SevenFiveSix** [Sachini/ronin#3]
Hi,thanks for your great work!
I try to use the pre-trained model to test my dataset, but I get stuck at the preprocessing pipeline. specifically, I find that the gen_dataset_v2.py only generate "processed/data.pkl", but I also find that ronin_resnet.py need something else like ori_error.json.(To be exactly, I find info.json miss some keys like gyro_integration_error, when I use --type unannotated with compile_dataset_h5.py)

so how can I generate complete processed data?

**Comment by SevenFiveSix** [comment]
I got it，I do some change of data load function that it works.But I find that the scale of my results is not correct, do you have some suggestion of that?

![20191030101121R_gsn](https://user-images.githubusercontent.com/45675492/67912789-ffc8f580-fbc5-11e9-917f-27ee822d14f0.png)
actually, I DO walk about 30 or 40 meters away and then walk back.

**Comment by SevenFiveSix** [comment]
solved it

**Comment by SevenFiveSix** [comment]
I also want to know that how can I get the corrected_tango

**Comment by Sachini** [comment]
The 'gen_dataset_v2.py' synchronise the data streams from one device. We have not included the data collection pipeline for two devices in this repository. Our supplementary document describes the data pipeline in detail (https://arxiv.org/pdf/1905.12853.pdf) but you would have to implement it yourself. 

As you have figured out the values in info.json file are only used for training and evaluation. If you only need to obtain the prediction, the values can be set to identity

**Comment by SevenFiveSix** [comment]
@Sachini 
HI,thanks for your reply. I think the pipeline in the paper may help me a lot.

And the scale problem is solved, just because the timestamp of my phone is 15-digits instead of 18-digits.

**Comment by oladipo123** [comment]
> Hi,thanks for your great work! I try to use the pre-trained model to test my dataset, but I get stuck at the preprocessing pipeline. specifically, I find that the gen_dataset_v2.py only generate "processed/data.pkl", but I also find that ronin_resnet.py need something else like ori_error.json.(To be exactly, I find info.json miss some keys like gyro_integration_error, when I use --type unannotated with compile_dataset_h5.py)
> 
> so how can I generate complete processed data?

Hello, may I ask how JSON files like ori_error.json are generated?
