### ISSUE TITLE
coordinate system clarification

### ISSUE THREAD

**Issue by hit2sjtu** [Sachini/ronin#31]
Hi, there
I tested your code and it works (RoNIN resnet) as expected under friendly motion. However I have some issues understanding the coordinate of the network inference output (vx,vy)? 
It is said in the paper:
_incorporates sensor fusion 3 into our data-driven system.  At test time, we use the coordinate frame deﬁned by system device orientations from Android or iOS, whose Z axis is aligned with gravity_
But from [android docs](https://developer.android.com/guide/topics/sensors/sensors_overview#sensors-coords), it seems Y axis is aligned with (negative) gravity.
Hopes you can help clarify my confusion. Thanks!

**Comment by Sachini** [comment]
We use the coordinate frame defined by system device orientation API. For Android, we use Game rotation vector ( https://source.android.com/devices/sensors/sensor-types#game_rotation_vector) so the input and output data are in reference frame of X-Y-Up where X-Y is chosen randomly by system for each sequence
