### ISSUE TITLE
dataset used for pretrained model

### ISSUE THREAD

**Issue by runfengdong** [Sachini/ronin#32]
Hi there,

I am trying to train ronin model with OXIOD dataset. I am wondering if the pretrained model you provide is training with both ronin dataset and OXIOD dataset together? Or you just use ronin dataset to train the pretrained model? And, from paper I know that you use Vicon orientation to train OXIOD dataset. Did you use Vicon orientation for testing OXIOD in ronin model?

 Many thanks!

**Comment by Sachini** [comment]
Hi, 

The pre-trained model is trained only on the RoNIN dataset (including the 50% of dataset that's not released publically)

For all the datasets,  we always used the device orientation estimated from IMU for testing. (_In training,_ when the IMU orientation is severely corrupted we used the ground-truth orientation)
