### ISSUE TITLE
RoNIN Dataset Missing

### ISSUE THREAD

**Issue by swapnilsayansaha** [Sachini/ronin#36]
I remember downloading the dataset ~5-6 months back. The dataset is no longer in the links provided (luckily I still have a copy).

**Comment by Sachini** [comment]
Thank you for pointing it out.

The dataset may be temporarily unavailable due to daily downloads limits imposed by Dropbox. If this is the case, it would be accessible after a day or two.

**Comment by Coderx7** [comment]
@Sachini : Seems they are down for good! neither dataset nor pretrained model is accessible, they give 404 Not found errors 
which is definitely not bandwidth related. 
Would appreciate if you could have a look and possibly provide a second mirror? (you can upload them on github if they are around 1GB, or use google drive, or mega.nz

**Comment by xhniu** [comment]
> Thank you for pointing it out.
> 
> The dataset may be temporarily unavailable due to daily downloads limits imposed by Dropbox. If this is the case, it would be accessible after a day or two.
 Can you upload the dataset and the pre-trained model to google drive or another website that can be accessed? The Dropbox links had crashed for a week.

**Comment by xhniu** [comment]
> I remember downloading the dataset ~5-6 months back. The dataset is no longer in the links provided (luckily I still have a copy).
Hi, would you like to share the file you copied! Thank you.

**Comment by xhniu** [comment]
@swapnilsayansaha Hi, would you like to share the file you copied! Thank you.

**Comment by xhniu** [comment]
@Sachini Can you upload the dataset and the pre-trained model to google drive or another website that can be accessed? The Dropbox links had crashed for a week.

**Comment by swapnilsayansaha** [comment]
I can't share the dataset without the author's permission.

**Comment by swapnilsayansaha** [comment]
I can't share the dataset without author's permission.

**Comment by Sachini** [comment]
Hi, sorry for the inconvenience. We're working on restoring the links.
Please email me (sherath@sfu.ca) if you need urgent access and I can provide a temporary link.

**Comment by xhniu** [comment]
@swapnilsayansaha Thank you all the same, I'd contacted the author.

**Comment by xhniu** [comment]
@Sachini I’ve emailed it to you, thank you.

**Comment by zhangjinglin888** [comment]
前段时间dropbox打开是40，不过现在没问题了

**Comment by Sachini** [comment]
updated the link
