### ISSUE TITLE
why did the way getitem features different between DenseSequenceDataset and  StridedSequenceDataset

### ISSUE THREAD

**Issue by dtneverdie** [Sachini/ronin#40]
Hello I am studying your project now. It does contribute a lot to indoor localization. I have a small issue about dataset part.
At data_glob_speed.py, in `class DenseSequenceDataset(Dataset):` ,which is working for lstm, the way getitem have a code of `feat = self.features[seq_id][frame_id - self.window_size:frame_id]`, while in 'class StridedSequenceDataset(Dataset):' working for resnet this part became `feat = self.features[seq_id][frame_id:frame_id + self.window_size]`. Why are those code different and it seems that the code behind would cause a error if the frame_id get window_size

**Comment by Sachini** [comment]
LSTM/ TCN uses SequenceToSequenceDataset. (DenseSequenceDataset is actually not used in our repo).  The difference is that Sequence to Sequence models predict for each input time step while Resnet predicts average velocity of input window. Note that` interval=window size` vs `interval =1` when loading data for StridedSequenceDataset vs SequenceToSequenceDataset.
