### ISSUE TITLE
running our own data

### ISSUE THREAD

**Issue by esteimle** [Sachini/ronin#41]
We collected a bunch of data with a phone and then tried to run compile_dataset_h5.py. The first thing it asks for is acce_calib.txt. I saw your answer to question #20 that says to use 0 and 1 for these values but that's not really the format for the acce_calib.txt file. The first thing the code does is try to parse a date out of it, and it wants at least four values per line according to the code.  

Do you have an example acce_calib.txt file you could share so I can get the format right? I guessed my way through compile_dataset_h5.py and generated the files only to hit another error at data_glob_speed: acce = np.array(self.info['imu_acce_scale']) * (acce_uncalib - np.array(self.info['imu_acce_bias']))  which makes me think I still have the format for that file wrong.

Oh and I noticed compile_dataset_h5 doesn't generate a few parameters that I'm guessing were manually calibrated and added such as: "gyro_integration_error": , "grv_ori_error": , "ekf_ori_error.  I read the supplementary material and the paper but it isn't clear to me how to generate those three.

Thanks for any help!

**Comment by Sachini** [comment]
Sorry for the confusion.

The format of acce_calib is below: 
The lines after the header contain 3 floating-point values each. The default value for bias/ scale are 0.0  / 1.0. 
```
# Created at <date> for <device>
<acce_bias_x> <acce_bias_y> <acce_bias_z>
<acce_scale_x> <acce_scale_y> <acce_scale_z>
```

For orientation errors: see section 3.2 of supplementary material. We evaluate the drift in orientation by performing spatial alignment at the end. The evaluation code is not shared here. The values were used to select the best orientation when training. At test time game rotation vector (grv) is always used.

**Comment by esteimle** [comment]
Thank you for the reply!  I guessed and I see now that I was a little off.  Thanks for the help.

**Comment by brentgti** [comment]
@Sachini, @esteimle:

From Sachini's post above, 

> At test time game rotation vector (grv) is always used.

Can you elaborate on how the game rotation vector is used? Do you run an app to generate some values that are saved to info.json (or a different file), put a value or additional code in 1 of the data-generating scripts (compile_dataset_h5 or a different one), or something else?

Thanks,
Brent

**Comment by crownz-sec** [comment]
> @Sachini, @esteimle:
> 
> From Sachini's post above,
> 
> > At test time game rotation vector (grv) is always used.
> 
> Can you elaborate on how the game rotation vector is used? Do you run an app to generate some values that are saved to info.json (or a different file), put a value or additional code in 1 of the data-generating scripts (compile_dataset_h5 or a different one), or something else?
> 
> Thanks, Brent

In RoNIN's Supplementary, the author says "We utilize Android’s game rotation vector as device orientations." at sec. 4.3
