### ISSUE TITLE
quaternion error?

### ISSUE THREAD

**Issue by HsiuWen** [Sachini/ronin#48]
file "dtat_glob_speed.py" line 52. You use quaternion.quaternion(*f['pose/tango_ori'][0]) for getting the first quaternion solution of the tangle. However, I checked the function definition, it should have arguments (w,x,y,z). But in README.txt which explains the format of hdf5 file, you wrote the format of tango_ori is in (x,y,z,w).

**Comment by Sachini** [comment]
Sorry for the confusion. The orientations in "synced" and "pose" groups are in (w, x, y, z) format. The README.txt refers to the datasets under "raw" group.
