### ISSUE TITLE
Problem running Pretrained model with CSV

### ISSUE THREAD

**Issue by fouad1995** [Sachini/ronin#5]
Hello Ms.Sachini, 

I run your model on test unseen data (RONIN) dataset and it works well , but my dataset is a csv file, so i want to run your pretrained network on my csv file .
i convert one of your data.hdf5 to csv file by open the HDF using HDF view and copy wanted data from it to csv file , then i run your model on this file but it didn't work , it draw only the ground truth data but didn't draw the predicted.
After debugging i found that the data size loaded from csv is longer than the data size of HDF5 
Could you give me some tips and tricks to run your model using CSV file .

and here's some screen shots of my debugging

![issue2](https://user-images.githubusercontent.com/34194529/74257753-ee7fa100-4cfd-11ea-8cf5-afe8c9429e8e.PNG)
![issue1](https://user-images.githubusercontent.com/34194529/74257755-efb0ce00-4cfd-11ea-92f8-a52f44aa62c0.PNG)

Thanks in advance, 
Fouad

**Comment by Sachini** [comment]
Hi,

The data loaders in this repository are can only load data from the file format of our dataset. (refer to data description on our website for more details).

To load data from a csv file, you can 1) write a new data loader (see ronin/source/data_utils.py ) or 2) convert to hdf5 (see ronin/source/preprocessing/compile_dataset_h5.py)
