### ISSUE TITLE
PDR outperforming TCN

### ISSUE THREAD

**Issue by gururajkosuru** [Sachini/ronin#6]
To begin, I am using the Recorder App after waiting for ~20 seconds and collecting the data. I do not  own a tango phone. My attempt currently is to only draw a graph using tcn without any groundtruth. 

I then load up all the data files into a single dataframe like ridi and add mock groundtruth data to be able to run the code. 

I noticed that the init_rotor information is picked from the tango data. I have attempted two methods around it:
* `ori =  game_rv directly and not using the init_rotor`
* `Changing the init_tango_ori = quaternion.quaternion(*[0.7071,0.7071,0,0])`
* Using the game rv value 0 as the init_rotor

Next, I run the tcn code and parallely just gather the game rv quaternion and convert it into euler angles. Next, I just use the cosine and sine and plot against x and y.

I should mention that I hold my phone up in front of my phone, screen facing my face and perpendicular to  ground. 

Here is my input data file:
[inputData.zip](https://github.com/Sachini/ronin/files/4442065/inputData.zip)

Here is the output from tcn:
![Screen Shot 2020-04-06 at 9 43 18 PM](https://user-images.githubusercontent.com/382374/78630883-ab4e3400-784f-11ea-9f5f-c98778d59553.png)

Here is the output from directly using the game_rv x and y angles(The X and Y axes are not scaled, so it is a bit skewed, but a simple inspection confirms it is close to the visually estimated path I have drawn at the end):
![Screen Shot 2020-04-06 at 9 44 29 PM](https://user-images.githubusercontent.com/382374/78630951-d6d11e80-784f-11ea-8ce3-41a6e5c8d359.png)

Here are the arguments I used
`
--model_path
/...<some-directory-path> ...checkpoints/ronin_tcn_checkpoint.pt
--feature_sigma
3
--window_size
1
`

I believe I am missing something here and this should be fairly better than the simple game_rv multiplication. 
![labelled](https://user-images.githubusercontent.com/382374/78631362-13e9e080-7851-11ea-8eec-d043fbbb7f1b.png)

Any help is much appreciated!

**Comment by gururajkosuru** [comment]
I realized I missed some details. I merge the raw data from all the files using 5 ms nearest merge strategy to populate a time indexed dataframe.

```
time_delta = '5ms'
gyro = pd.read_csv(mypath + 'gyro.txt', delimiter=' ', comment='#')#, names = ['time','gyro_x','gyro_y','gyro_z'])
gyro['time'] = pd.to_datetime(gyro['time'], unit='ns')
print(gyro.shape)

linacce = pd.read_csv(mypath + 'acce.txt', delimiter=' ', comment='#')#, names = ['time','acce_x','acce_y','acce_z'])
linacce['time'] = pd.to_datetime(linacce['time'], unit='ns')
print(linacce.shape)
print(imu_all.shape)
imu_all = pd.merge_asof(gyro, linacce,on='time',tolerance=pd.Timedelta(time_delta), direction=match_critertia)
imu_all['time'] = pd.to_datetime(imu_all['time'], unit='ns')
imu_all = imu_all.sort_values(by='time')
print(imu_all.shape)

game_rv = pd.read_csv(mypath + 'game_rv.txt', delimiter=' ', comment='#')#, names = ['time', 'rv_w', 'rv_x', 'rv_y', 'rv_z'])
game_rv['time'] = pd.to_datetime(game_rv['time'], unit='ns')
print(game_rv.shape)
print(imu_all.shape)

imu_all = imu_all.sort_values(by='time')
imu_all = pd.merge_asof(imu_all, game_rv,on='time',tolerance=pd.Timedelta(time_delta), direction=match_critertia)
imu_all['time'] = pd.to_datetime(imu_all['time'], unit='ns')
```

I am also attaching the graphs for the gyroscope, accelerometer, the game rv in euler angles in x,y,z and finally the path using only the game_rv and converting to cosine/sine:
![Screen Shot 2020-04-06 at 10 08 56 PM](https://user-images.githubusercontent.com/382374/78632238-63c9a700-7853-11ea-89b5-3953bbc87f0b.png)

**Comment by Sachini** [comment]
Game rotation vector reference frame is defined each time an API listner is registered so you cannot align different sessions using the game rotation vector. (This is the same way as Tango reference frame). The trajectory output is _relative to the reference frame of rotation vector_. This can be reference frame of game rotation vector (init rotor is identity) or Tango reference frame, which we use in training to compare but not necessary when predicting. 

Accelerometer, gyroscope or game rotation vector does not contain any information to enable horizontal alignment, threfore only way to align different sessions is to use external information. If your trajectories are outdoors I would suggest using calibrated magnet directions.

Also the window size and feature sigma given in the command are not ideal. If you're using the pretrained models, please use the configuration found in https://github.com/Sachini/ronin/blob/master/config/temporal_model_defaults.json
If you're training a model I should suggest a window size >= receptive field and a very small feature sigma.

**Comment by Sachini** [comment]
Game rotation vector reference frame is defined each time an API listner is registered so you cannot align different sessions using the game rotation vector. (This is the same way as Tango reference frame). The trajectory output is relative to the reference frame of rotation vector. This can be reference frame of game rotation vector (init rotor is identity, i.e [1, 0. 0. 0]) or Tango reference frame, which we use in training to compare but not necessary when predicting.

This is the result I get from TCN 
![image](https://user-images.githubusercontent.com/4003160/78833683-2162b000-79a2-11ea-83fc-04ffd1721c08.png)

For processing data I would suggest using interpolation rather than nearest value to be consistent with training data (https://github.com/Sachini/ronin/blob/master/source/preprocessing/gen_dataset_v2.py)

Also the window size and feature sigma given in the command are incorrect. If you're using the pretrained models, please use the configuration found in https://github.com/Sachini/ronin/blob/master/config/temporal_model_defaults.json
If you're training a model I should suggest a window size >= receptive field and a very small feature sigma.

**Comment by gururajkosuru** [comment]
Thanks for the quick and detailed response along with outputs from the data I shared. 
* I have switched to interpolation
* I have switched to adding the defaults into my args 
```
ronin_lstm_tcn.py 

test
--dataset
ridi
--type
tcn
--test_list
....<prefix>.../test
--data_dir
....<prefix>.../data/
--out_dir
.....<>
--model_path
....<prefix>.../ronin_tcn/checkpoints/ronin_tcn_checkpoint.pt
--batch_size
72
--epochs
1000,
--save_interval
20
--step_size
100
--lr
0.0003
num_workers
1
window_size
400
feature_sigma
0.001
--target_sigma
0.0
--file
seq2seq_models
--kernel_size
3
--channels
32,64,128,256,72,36
--layer_size
100
--layers
3
--device
cpu
```

* I am using two init_rotor configs:
** [1,0,0,0] 
** First reading from the rv
The results are still way off compared to the ones you shared. Do you see anything else I am missing here?
![Screen Shot 2020-04-08 at 7 51 57 PM](https://user-images.githubusercontent.com/382374/78852897-6ef71100-79d2-11ea-8e44-3d605551d64e.png)

**Comment by gururajkosuru** [comment]
Thanks for the inputs. This has been very helpful. Posting this for closing out the issue and for anyone else in the future who might face similar issues.

I had 2  issues I had to fix to make this work: 
* https://github.com/Sachini/ronin/blob/master/source/data_ridi.py#L41 was reducing from nanoseconds but the input data from https://github.com/Sachini/ronin/blob/master/source/preprocessing/gen_dataset_v2.py was already using seconds. So just commenting out the division to nanos helped
* I used init_tango_ori = quaternion.quaternion(*imu_all[['rv_w', 'rv_x', 'rv_y', 'rv_z']].values[0])

I guess the default skip front and end are making my plot missing the head and tails. 
![Screen Shot 2020-04-09 at 4 21 23 PM](https://user-images.githubusercontent.com/382374/78948811-6fe57c80-7a7e-11ea-907e-251405e12524.png)
I have broad stroke colors set on every 6th to debug if something goes wrong better.
