### ISSUE TITLE
Clarification on Data Processing

### ISSUE THREAD

**Issue by jgochal** [Sachini/ronin#7]
Hi - I wanted to confirm is this the correct way that one would process their own data:

For RONIN-style data collected from, e.g., the Android app, we first process it with `gen_dataset_v2.py` and then use the results of that (especially the pickle file) with `compile_dataset_h5.py`

Any feedback would be much appreciated.

Thanks,

Joe

**Comment by Sachini** [comment]
If you use our app to collect data on a single file you can use `compile_dataset_h5.py` with `--type unannotated`

For two devices, we have published the entire pre-processing pipeline. But the details are in the paper for implementation
